name: RunTests

on: [push, pull_request]

jobs:
  build-for-ui-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup UI testing env
        run: |
          export DISPLAY=:99.0
          Xvfb -ac :99 -screen 0 1920x1080x16 &
          gradle runIdeForUiTests &
      - name: Sleep 180s & run the UI tests
        run: sleep 180s && gradle uiTest
